import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Page from "@/components/templates/Top/Page";
import { GetStaticProps, NextPage } from "next";
import { getZennRssFeed, getHatenaRssFeed, FeedItem } from "@/lib/feed";

type Props = {
  feedItems: FeedItem[];
};

const Home: NextPage<Props> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Page feedItems={props.feedItems} />
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const zennArticles = await getZennRssFeed();
  const hatenaArticles = await getHatenaRssFeed();

  const result = ([] as FeedItem[])
    .concat(zennArticles)
    .concat(hatenaArticles)
    .sort((a, b) => (a.createdAt < b.createdAt ? 1 : -1));

  return {
    props: { feedItems: result },
  };
};
